# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  before_all do
    # https://docs.fastlane.tools/actions/carthage/
    carthage(platform: "iOS", use_netrc: false, cache_builds: true, use_binaries: false, use_xcframeworks: true)
  end
  
  lane :adhoc do
    setup_ci

    match(
      type: "adhoc",
      readonly: true,
      git_url: "https://github.com/fvh-P/Cider-certificates.git",
      git_basic_authorization: Base64.strict_encode64("#{ENV["GITHUB_USERNAME"]}:#{ENV["GITHUB_PERSONAL_ACCESS_TOKEN"]}"),
      storage_mode: "git",
      app_identifier: "net.fvhp.lily.Cider",
      username: ENV["APPLE_ID"]
    )

    increment_build_number

    build_app(
      scheme: "Cider AdHoc",
      output_directory: "./",
      export_options: {
        method: "ad-hoc",
        manifest: {
            appURL: "https://dev.cider.lily.fvhp.net/Cider.ipa",
            displayImageURL: "https://dev.cider.lily.fvhp.net/image57.png",
            fullSizeImageURL: "https://dev.cider.lily.fvhp.net/image512.png"
        },
        provisioningProfiles: {
            "net.fvhp.lily.Cider" => "match AdHoc net.fvhp.lily.Cider"
        }
      }
    )
  end

  lane :beta do
    setup_ci

    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      in_house: false,
    )

    match(
      type: "appstore",
      readonly: true,
      git_url: "https://github.com/fvh-P/Cider-certificates.git",
      git_basic_authorization: Base64.strict_encode64("#{ENV["GITHUB_USERNAME"]}:#{ENV["GITHUB_PERSONAL_ACCESS_TOKEN"]}"),
      storage_mode: "git",
      app_identifier: "net.fvhp.lily.Cider",
      username: ENV["APPLE_ID"],
    )

    increment_build_number

    build_app(
      scheme: "Cider TestFlight",
      output_directory: "./",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
            "net.fvhp.lily.Cider" => "match AppStore net.fvhp.lily.Cider"
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
    )
  end
end
