name: AdHoc Deployment

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -s '/Applications/Xcode_12.5.app/Contents/Developer'
    - uses: actions/cache@v2
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
        restore-keys: |
          ${{ runner.os }}-carthage-
    - name: Run fastlane adhoc
      env:
        GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
        GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
      run: |
        fastlane adhoc
    - name: Setup AWS CLI
      env:
        ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
        SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SECURITY_GROUP: ${{ secrets.AWS_SECURITY_GROUP_ID }}
      run: |

        # AWS CLIをインストール
        curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
        sudo installer -pkg AWSCLIV2.pkg -target /
        aws --version

        # AWS CLIに設定をする
        printf "${ACCESS_KEY}\n${SECRET_ACCESS_KEY}\n${AWS_REGION}\njson\n" | aws configure --profile cider-adhoc-deploy
        aws configure get aws_access_key_id --profile cider-adhoc-deploy
    - name: prepare .ssh dir
      run: mkdir -p .ssh && chmod 700 .ssh
    - name: ssh key generate
      run: echo "$SSH_KEY" > .ssh/id_ed25519 && chmod 600 .ssh/id_ed25519
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.2
    - name: open port and deploy
      env:
        SECURITY_GROUP: ${{ secrets.AWS_SECURITY_GROUP_ID }}
        SCP_DESTINATION: ${{ secrets.SCP_DESTINATION }}
      run: |
        # https://github.com/haythem/public-ip
        IP_ADDRESS=`echo ${{ steps.ip.outputs.ipv4 }}`
        
        # SSHポートを開放する
        aws --profile cider-adhoc-deploy ec2 authorize-security-group-ingress --group-id ${SECURITY_GROUP} --protocol tcp --port 22 --cidr "$IP_ADDRESS"/32
        
        # ポートが開放されたことを確認
        while true; do aws ec2 --profile cider-adhoc-deploy describe-security-groups --group-ids ${SECURITY_GROUP} | grep -q "\"CidrIp\": \"$IP_ADDRESS/32\"" && break; sleep 5; done
        
        # SCPでファイルをコピー
        scp -i .ssh/id_ed25519 -oStrictHostKeyChecking=no Cider.ipa manifest.plist $SCP_DESTINATION
      timeout-minutes: 5
    - name: close port
      env:
        SECURITY_GROUP: ${{ secrets.AWS_SECURITY_GROUP_ID }}
      run: |
        # https://github.com/haythem/public-ip
        IP_ADDRESS=`echo ${{ steps.ip.outputs.ipv4 }}`

        # SSHのポートを閉じる
        aws --profile cider-adhoc-deploy ec2 revoke-security-group-ingress --group-id ${SECURITY_GROUP} --protocol tcp --port 22 --cidr "$IP_ADDRESS"/32
