name: AdHoc Deployment

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -s '/Applications/Xcode_12.5.app/Contents/Developer'
    - uses: actions/cache@v2
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
        restore-keys: |
          ${{ runner.os }}-carthage-
    - name: Run fastlane adhoc
      env:
        GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
        GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
      run: |
        fastlane adhoc
    - name: Setup AWS CLI
      env:
        ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
        SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |

        # AWS CLIをインストール
        curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
        sudo installer -pkg AWSCLIV2.pkg -target /
        aws --version

        # AWS CLIに設定をする
        printf "${ACCESS_KEY}\n${SECRET_ACCESS_KEY}\n${AWS_REGION}\njson\n" | aws configure --profile cider-adhoc-deploy
        aws configure get aws_access_key_id --profile cider-adhoc-deploy
    - name: deploy to S3
      env: 
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      run: |
        aws --profile cider-adhoc-deploy s3 cp . s3://${S3_BUCKET_NAME} --exclude "*" --include "Cider.ipa" --include "manifest.plist" --recursive
