# This is a basic workflow to help you get started with Actions

name: Ad Hoc Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -s '/Applications/Xcode_12.4.app/Contents/Developer'
    - name: Run fastlane certificate_adhoc
      env:
        GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
        GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
      run: |
        fastlane certificate_adhoc
    - name: Run fastlane adhoc
      run: |
        fastlane adhoc
    - name: prepare .ssh dir
      run: mkdir -p .ssh && chmod 700 .ssh
    - name: ssh key generate
      run: echo "$SSH_KEY" > .ssh/id_ed25519 && chmod 600 .ssh/id_ed25519
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
    - name: copy ipa and manifest files
      run: scp -i .ssh/id_ed25519 Cider.ipa manifest.plist $SCP_DESTINATION
      env:
        SCP_DESTINATION: ${{ secrets.SCP_DESTINATION }}
